conf/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('datatables.urls', namespace='datatables')),

]

datatables/urls.py
from django.urls import path 
from .views import index, strava_auth, strava_callback
app_name = 'datatables'

urlpatterns = [
    path('strava/auth/', strava_auth, name='strava_auth'),
    path('stravacallback/', strava_callback, name='strava_callback'), 
    path('', index, name='index'),
]

datatables/models.py
import requests
from django.db import models
from django.conf import settings 
from django.contrib.auth import get_user_model
from django.db import models

class Basetable(models.Model):
	basetable_id = models.AutoField(primary_key=True)
	comment_count = models.CharField(max_length=100)
	has_kudoed = models.BooleanField()
	device_watts = models.BooleanField()
	type = models.CharField(max_length=100)
	end_latlng = models.CharField(max_length=100)
	upload_id_str = models.CharField(max_length=100)
	id = models.CharField(max_length=100)
	kudos_count = models.CharField(max_length=100)
	kilojoules = models.CharField(max_length=100)
	visibility = models.CharField(max_length=100)
	athlete_count = models.CharField(max_length=100)
	resource_state = models.CharField(max_length=100)
	max_speed = models.CharField(max_length=100)
	from_accepted_tag = models.BooleanField()
	start_latlng = models.CharField(max_length=100)
	achievement_count = models.CharField(max_length=100)
	name = models.CharField(max_length=100)
	commute = models.BooleanField()
	utc_offset = models.CharField(max_length=100)
	average_cadence = models.CharField(max_length=100)
	private = models.BooleanField()
	upload_id = models.CharField(max_length=100)
	distance = models.CharField(max_length=100)
	timezone = models.CharField(max_length=100)
	location_country = models.CharField(max_length=100)
	has_heartrate = models.BooleanField()
	external_id = models.CharField(max_length=100)
	location_state = models.CharField(max_length=100)
	manual = models.BooleanField()
	gear_id = models.CharField(max_length=100)
	flagged = models.BooleanField()
	trainer = models.BooleanField()
	start_latitude = models.CharField(max_length=100)
	workout_type = models.CharField(max_length=100)
	location_city = models.CharField(max_length=100)
	total_photo_count = models.CharField(max_length=100)
	elapsed_time = models.IntegerField()
	heartrate_opt_out = models.BooleanField()
	display_hide_heartrate_option = models.BooleanField()
	average_speed = models.CharField(max_length=100)
	average_temp = models.IntegerField()
	moving_time = models.IntegerField()
	start_date = models.CharField(max_length=100)
	pr_count = models.CharField(max_length=100)
	start_date_local = models.CharField(max_length=100)
	total_elevation_gain = models.CharField(max_length=100)
	average_watts = models.CharField(max_length=100)
	start_longitude = models.CharField(max_length=100)
	photo_count = models.CharField(max_length=100)
	max_watts = models.IntegerField()
	weighted_average_watts = models.IntegerField()
	
class Athlete(models.Model):
	basetable_id = models.OneToOneField(Basetable,on_delete=models.CASCADE)
	athlete_id = models.AutoField(primary_key=True)
	resource_state = models.CharField(max_length=100)
	id = models.IntegerField()
	
class Map(models.Model):
	basetable_id = models.OneToOneField(Basetable,on_delete=models.CASCADE)
	map_id = models.AutoField(primary_key=True)
	summary_polyline = models.CharField(max_length=100)
	id = models.CharField(max_length=100)
	resource_state = models.CharField(max_length=100)
	

class StravaActivity(models.Model): 
    name = models.CharField(max_length=200, null=True, blank=True)
    distance = models.CharField(max_length=200, null=True, blank=True)
    moving_time = models.CharField(max_length=200, null=True, blank=True)
    elapsed_time = models.CharField(max_length=200, null=True, blank=True)
    total_elevation_gain = models.CharField(max_length=200, null=True, blank=True)
    workout_type = models.CharField(max_length=200, null=True, blank=True)
    start_date = models.CharField(max_length=200, null=True, blank=True)
    location_city = models.CharField(max_length=200, null=True, blank=True)
    location_state = models.CharField(max_length=200, null=True, blank=True)
    location_country = models.CharField(max_length=200, null=True, blank=True)
    achievement_count = models.CharField(max_length=200, null=True, blank=True)
    kudos_count = models.CharField(max_length=200, null=True, blank=True)
    comment_count = models.CharField(max_length=200, null=True, blank=True)
    photo_count = models.CharField(max_length=200, null=True, blank=True)
    average_speed = models.CharField(max_length=200, null=True, blank=True)
    max_speed = models.CharField(max_length=200, null=True, blank=True)
    average_temp = models.CharField(max_length=200, null=True, blank=True)
    average_watts = models.CharField(max_length=200, null=True, blank=True)
    pr_count = models.CharField(max_length=200, null=True, blank=True)
    has_kudoed = models.CharField(max_length=200, null=True, blank=True)

class StravaToken(models.Model): 
    user = models.OneToOneField(
        get_user_model(), 
        on_delete=models.CASCADE
    )
    token_type = models.CharField(max_length=200)
    refresh_token = models.CharField(max_length=1200)
    access_token = models.CharField(max_length=1200)
    strava_id = models.CharField(max_length=200)
    strava_username = models.CharField(max_length=200)

    def __str__(self): 
        return self.user.username

    def get_activities(self): 
        auth_header = {
            'accept': 'application/json',
            'Authorization': 'Bearer ' + self.access_token,
        }
        url = 'https://www.strava.com/api/v3/athlete/activities?per_page=100'

        return requests.get(url, headers=auth_header).json()

    def get_miles(self): 
        auth_header = {
            'accept': 'application/json',
            'Authorization': 'Bearer ' + self.access_token,
        }
        url = f"https://www.strava.com/api/v3/athletes/{self.strava_id}/stats"

        return requests.get(url, headers=auth_header)

    def sync_activities(self): 
        activities = self.get_activities()
        for strava in activities: 
            activity = StravaActivity()
            activity.name = strava.get('name', '')
            activity.distance = strava.get('distance', '')
            activity.moving_time = strava.get('moving_time', '')
            activity.elapsed_time = strava.get('elapsed_time', '')
            activity.total_elevation_gain = strava.get('total_elevation_gain', '')
            activity.workout_type = strava.get('workout_type', '')
            activity.start_date = strava.get('start_date', '')
            activity.location_city = strava.get('location_city', '')
            activity.location_state = strava.get('location_state', '')
            activity.location_country = strava.get('location_country', '')
            activity.achievement_count = strava.get('achievement_count', '')
            activity.kudos_count = strava.get('kudos_count', '')
            activity.comment_count = strava.get('comment_count', '')
            activity.photo_count = strava.get('photo_count', '')
            activity.average_speed = strava.get('average_speed', '')
            activity.max_speed = strava.get('max_speed', '')
            activity.average_temp = strava.get('average_temp', '')
            activity.average_watts = strava.get('average_watts', '')
            activity.pr_count = strava.get('pr_count', '')
            activity.has_kudoed = strava.get('has_kudoed', '')
            activity.save()





    

datatables/views.py
import requests

from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import get_user_model
from django.conf import settings
from .models import StravaActivity, StravaToken
User = get_user_model()

# strava call back 
def callback_url(id, callbackuri): 
    """Process call back"""
    return f'http://www.strava.com/oauth/authorize?client_id={id}&response_type=code&redirect_uri={callbackuri}&approval_prompt=force&scope=activity:read'
    

def strava_auth(request):     
    """Auth"""
    callback = callback_url(
        id = settings.STRAVA_CLIENT , 
        callbackuri = 'http://0d6a-72-229-100-170.ngrok.io/stravacallback'
        )
    return redirect(callback)

def strava_callback(request): 

    resp_token = requests.post('https://www.strava.com/oauth/token', 
        data = {
            'client_id': settings.STRAVA_CLIENT, 
            'client_secret': settings.STRAVA_SECRET, 
            'code': request.GET.get('code'), 
            'grant_type': 'authorization_code'
    })

    if resp_token.status_code == 200:
        resp_token = resp_token.json()
    
    if resp_token['athlete']['username'] is None: 
        resp_token['athlete']['username'] = resp_token['athlete']['firstname']

    try:
        token = StravaToken.objects.get(user=request.user)
        token.token_type = resp_token.get('token_type'),
        token.refresh_token = resp_token.get('refresh_token')
        token.access_token = resp_token.get('access_token')
        token.strava_id = resp_token.get('athlete').get('id')
        token.strava_username = resp_token.get('athlete').get('username')
        token.save()
    except:  
        token = StravaToken(
            user=request.user,
            # token=request.GET.get('code'), 
            token_type = resp_token.get('token_type'), 
            refresh_token = resp_token.get('refresh_token'),
            access_token = resp_token.get('access_token'),
            strava_id = resp_token.get('athlete').get('id'),
            strava_username = resp_token.get('athlete').get('username')
        )
        token.save()

    return redirect('/')
    


def index(request): 
    activities = StravaActivity.objects.all()
    return render(request, 'datatables/index.html', {'activities': activities})

datatables/templates/datatables/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container m-5">
    <div class="project-info-box">
        <a class="btn btn-primary" href="{% url 'datatables:strava_auth' %}" role="button">Strava Login</a>
    </div>
</div>

<div class="container my-5">
    
    <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>name</th>
                <th>distance</th>
                <th>moving_time</th>
                <th>elapsed_time</th>
                <th>total_elevation_gain</th>
                <th>start_date</th>
                <th>location_country</th>
                <th>achievement_count</th>
                <th>kudos_count</th>
                <th>comment_count</th>
                <th>photo_count</th>
                <th>average_speed</th>
                <th>max_speed</th>
                <th>average_temp</th>
                <th>average_watts</th>
                <th>pr_count</th>
            </tr>
        </thead>
        <tbody>
            {% for activity in activities %}    
                <tr>
                    <td>{{activity.name}}</td>  
                    <td>{{activity.distance}}</td>  
                    <td>{{activity.moving_time}}</td>   
                    <td>{{activity.elapsed_time}}</td>  
                    <td>{{activity.total_elevation_gain}}</td>  
                    
                    <td>{{activity.start_date}}</td>        
                    <td>{{activity.location_country}}</td>  
                    <td>{{activity.achievement_count}}</td> 
                    <td>{{activity.kudos_count}}</td>   
                    <td>{{activity.comment_count}}</td> 
                    <td>{{activity.photo_count}}</td>   
                    <td>{{activity.average_speed}}</td> 
                    <td>{{activity.max_speed}}</td> 
                    <td>{{activity.average_temp}}</td>  
                    <td>{{activity.average_watts}}</td> 
                    <td>{{activity.pr_count}}</td>  
                    
                </tr>
            {% endfor %}
        </tfoot>
    </table>
</div>

{% endblock content %}

{% block js %}
    {% comment %} <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.bundle.min.js"></script> {% endcomment %}
    {% comment %} <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.3/b-2.2.1/b-html5-2.2.1/cr-1.5.5/date-1.1.1/r-2.2.9/sb-1.3.0/sp-1.4.0/datatables.min.js"></script>         {% endcomment %}
    
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>

{% comment %} 
    <script>
        $(document).ready(function() {
            $('#example').DataTable( {
                select: true
            } );
        } );
    </script> 
{% endcomment %}

<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            dom: 'Bfrtip',
            select: true,
            buttons: [
                {
                    text: 'Select all',
                    action: function () {
                        table.rows().select();
                    }
                },
                {
                    text: 'Select none',
                    action: function () {
                        table.rows().deselect();
                    }
                }
            ]
        } );
    } );
</script>
{% endblock js %}